# Generated by Django 6.0.4 on 2026-06-04 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
        ('kanban_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='boards.board'),
        ),
        migrations.DeleteModel(
            name='Board',
        ),
    ]
