# Generated by Django 6.0.4 on 2026-05-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0002_task_assignee_task_description_task_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='comments',
            field=models.IntegerField(default=0),
        ),
    ]
