# Generated by Django 6.0.4 on 2026-05-21 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0006_remove_task_created_by_comment_owner_task_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='owner',
        ),
    ]
