# Generated by Django 6.0.4 on 2026-05-27 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0009_alter_task_assignee_alter_task_reviewer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='owner',
        ),
    ]
