# Generated by Django 6.0.4 on 2026-05-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_remove_task_board_delete_board_delete_task'),
        ('kanban_app', '0011_alter_board_member_alter_comment_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='member',
            field=models.ManyToManyField(related_name='boards', to='auth_app.userprofile'),
        ),
    ]
