# Generated by Django 6.0.4 on 2026-05-03 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_board_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='board',
        ),
        migrations.DeleteModel(
            name='Board',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
